/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import java.awt.Dimension;

/**
 *
 * @author Administrador
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form Menu1
     */
    public MenuAdministrador() {
        this.setMinimumSize(new Dimension(420, 920));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 120, 0, 2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 160, 120);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 140, 400, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, -16, 410, 150);

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel5.setText("Ingreso de libros");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 160, 180, 19);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(260, 200, 140, 10);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 200, 130, 10);

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel6.setText("Titulo     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 260, 110, 19);

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel7.setText("Autor      :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 300, 110, 19);

        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel8.setText("Editorial  :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 340, 110, 19);

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel9.setText("Disponible :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 390, 150, 19);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 220, 220, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(140, 260, 220, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(140, 300, 220, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 340, 220, 30);

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel10.setText("Codigo     :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 220, 150, 19);

        jButton1.setText("Actualizar");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 820, 90, 23);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 500, 400, 10);

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel11.setText("Consultas y Modificaciones");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 530, 250, 19);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(260, 570, 140, 10);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(0, 570, 130, 10);

        jLabel12.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel12.setText("Titulo     :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 630, 110, 19);

        jLabel13.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel13.setText("Autor      :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 670, 110, 19);

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel14.setText("Editorial  :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 710, 110, 19);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 590, 220, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(140, 630, 220, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(140, 670, 220, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(140, 710, 220, 30);

        jLabel15.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel15.setText("Codigo     :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 590, 150, 19);

        jButton2.setText("Guardar");
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 460, 90, 23);

        jButton3.setText("Consultar");
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 820, 90, 23);

        jRadioButton1.setText("Si");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 390, 33, 23);

        jRadioButton2.setText("No");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(140, 420, 39, 23);

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 0, 18)); // NOI18N
        jLabel16.setText("Disponible :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 750, 150, 19);

        jRadioButton3.setText("Si");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(140, 750, 33, 23);

        jRadioButton4.setText("No");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(140, 780, 39, 23);

        jMenuBar2.setBackground(new java.awt.Color(0, 204, 204));

        jMenu6.setText("Opciones");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Prestamo de libro");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jRadioButtonMenuItem2);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar2.add(jMenu6);

        jMenu1.setText("Contacto");

        jMenuItem4.setText("Email");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Acerca de nosotros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        Prestamo prestameunlibro = new Prestamo();
        prestameunlibro.setVisible(true); 
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void DISPOSE_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
